### ISSUE TITLE
Ubuntu-Mate 18.04 - Welcome and Software Boutique Blank Screens

### ISSUE THREAD

**Issue by finbarrcnaipe** [ubuntu-mate/ubuntu-mate-welcome-legacy#64]
Did not see this posted here on GitHub, but there are several threads found using google...with no remedy that I can see.

Toshiba Satellite 1135 Laptop...older machine:
Intel 2.0GHz Mobile Celeron CPU
1GB RAM
Intel 82852/855GM Graphics.  Kernel module is i915,intelfb.   
32bit Ubuntu-Mate.

Older machine, so that is the primary reason Ubuntu-Mate 32bit was selected...to create a working, viable box using older/obsolete laptop.

- After Ubuntu-mate clean install CD 16.04, Welcome and Software Boutique work as expected.
- After Upgrade 16.04 to latest auto-updates, Welcome & Software Boutique give blank screens.

- After Ubuntu-mate clean install CD 18.04, Welcome and Software Boutique give blank screens.

I'm on 18.04 at this point, so not going to downgrade back to 16.04.

So far, this issue appears to be isolated to Welcome and Software Boutique.

Uninstalled:  snap remove ubuntu-mate-welcome
Reinstalled:  snap install ubuntu-mate-welcome --classic

No joy.

Don't really care so much about Welcome, but would appreciate being able to use Software Boutique.

Other than this issue, Ubuntu-mate works very well on Toshiba Satellite 1135, and has fully extended it's useful life for my purposes.

As I say, I've seen some posts on Ubuntu-mate and Ubuntu forums with folks reporting this issue.  However, I have not seen any solutions posted that work (or sometimes even apply) to this situation.

Is there an older version (as in the version in 16.04 Install CD) that can be installed?  Is there a fix for the latest version?

**Comment by lah7** [comment]
Please avoid duplicate posting: [https://ubuntu-mate.community/t/welcome-screen-and-software-boutique-screens-are-blank/10513/23](https://ubuntu-mate.community/t/welcome-screen-and-software-boutique-screens-are-blank/10513/23?u=lah7)

Unfortunately, the "blank screen" issue not tied to Welcome or Boutique, but affects any WebKit2-based application due to external factors (likely graphics card/driver or something else). It seems another user found a solution that worked for you by forcing software OpenGL:

    LIBGL_ALWAYS_SOFTWARE=1 ubuntu-mate-welcome

**Comment by finbarrcnaipe** [comment]
Got it...OpenGL issue w/older Graphic card (Intel) using mesa driver w/older version of OpenGL (1.03).

Legacy HW owners beware...
