### ISSUE TITLE
Sonar has been discontinued

### ISSUE THREAD

**Issue by philipzae** [ubuntu-mate/ubuntu-mate-welcome-legacy#80]
On the features tab under accessibility, it mentions 'Sonar GNU/Linux' and links to the link below and it mentions there that sonar is discontinued.

https://distrowatch.com/table.php?distribution=sonar

**Comment by lah7** [comment]
What would you suggest we do with this statement?

> Ubuntu MATE is never going to be able to offer the comprehensive integration of assistive technologies that **Sonar GNU/Linux** provides. But Ubuntu MATE will continue to follow their lead so that Ubuntu MATE is a viable desktop solution where computer access is shared within a household or business where individual needs differ.

[(Sonar is also referenced on the website's roadmap)](https://ubuntu-mate.org/faq/roadmap/#accessibility)

This paragraph seems fine to me. Even though Sonar is a discontinued product, it's being praised for its accessibility features at the time. :star: I haven't used Sonar myself, but I trust the original author's word about it.

It's too late in the 20.04 cycle to make text changes, but happy to hear feedback.

**Comment by philipzae** [comment]
Should be discussed with your team how you'd want to change it. Sonar has been discontinued for I believe more than 2 years. Its last release was in 2016.

**Comment by lah7** [comment]
It turns out one of our team members, @goinglinux, actually wrote documentation for Sonar. :+1: 

While it's true Sonar has been discontinued, the paragraph refers to its accomplishment of putting in the efforts to ensure accessibility works out of the box, which is [an objective for this project](https://ubuntu-mate.org/about/). The first sentence in particular refers to extra utilities that Sonar supported as standard which Ubuntu MATE doesn't - such as head-and-eye tracking software, braille technology integration and others.

**Comment by philipzae** [comment]
At least i would suggest changing it to 'that Sonar GNU/Linux once provides.'
